

services:
  postgres-db:
    image: postgres:18.4
    container_name: ken-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testK
    volumes:
      - ken-postgres-vol:/var/lib/postgresql

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ken-mailhog
    logging:
      driver: 'none'
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  ken-postgres-vol: