CREATE SEQUENCE IF NOT EXISTS administrators_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS groups_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS professors_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS students_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE administrators
(
    id       BIGINT NOT NULL,
    username VARCHAR(255),
    user_id  BIGINT,
    CONSTRAINT pk_administrators PRIMARY KEY (id)
);

CREATE TABLE groups
(
    id   BIGINT NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

CREATE TABLE groups_professors
(
    group_id     BIGINT NOT NULL,
    professor_id BIGINT NOT NULL
);

CREATE TABLE professors
(
    id           BIGINT NOT NULL,
    user_id      BIGINT,
    fio          VARCHAR(255),
    phone_number VARCHAR(255),
    email        VARCHAR(255),
    CONSTRAINT pk_professors PRIMARY KEY (id)
);

CREATE TABLE students
(
    id             BIGINT NOT NULL,
    user_id        BIGINT,
    fio            VARCHAR(255),
    phone_number   VARCHAR(255),
    email          VARCHAR(255),
    study_group_id BIGINT,
    CONSTRAINT pk_students PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    role     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE groups
    ADD CONSTRAINT uc_groups_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE administrators
    ADD CONSTRAINT FK_ADMINISTRATORS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE professors
    ADD CONSTRAINT FK_PROFESSORS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_STUDYGROUP FOREIGN KEY (study_group_id) REFERENCES groups (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE groups_professors
    ADD CONSTRAINT fk_gropro_on_group FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE groups_professors
    ADD CONSTRAINT fk_gropro_on_professor FOREIGN KEY (professor_id) REFERENCES professors (id);